### ISSUE TITLE
Unable to Install Youtube Vanced

### ISSUE THREAD

**Issue by DrPleaseRespect** [YTVanced/VancedManager#435]
**Please only report your issue here, if all points below are true**
- I installed the App from [vancedapp.com](https://vancedapp.com), this github repository or the Vanced Discord server
- I am using the latest version
- This is an issue in the Vanced Manager app (NOT Youtube Vanced/Music)
- This issue keeps re-occurring every time I try
- For MIUI users: I disabled MIUI optimisations

**Phone Specifications:**
- Brand: Realme 3 (RMX1821)
- Operating System: Android
- Android Version: 9
- Vanced Manager Version: 2.5.1 (Weed)

**Please describe the problem you are having in as much detail as possible:**
When ever I try to install Youtube Vanced I get Failure [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install com.google.android.youtube without first uninstalling]

**Steps to reproduce:**
Youtube installed as a System App
Install Youtube Vanced from VancedManager using root method

**Further details:**

**Comment by DrPleaseRespect** [comment]
After Downgrading Vanced Manager to 2.5.0
Problem is fixed

**Comment by X1nto** [comment]
you were probably trying to downgrade which won't work

**Comment by bdotq** [comment]
I can confirm I also have this issue. 
Downloaded vanced manager 2.5.1 and also got the INSTALL_FAILED_ALREADY_EXISTS error while trying to root install.
Tried 2.5.0 and the install works perfect. Thanks @DrPleaseRespect 

Android 7.1.1 & Magisk

**Comment by DrPleaseRespect** [comment]
> you were probably trying to downgrade which won't work

The version of the youtube app was the oldest one after uninstalling updates in the settings. Even after doing that, the apl would still not install..

**Comment by X1nto** [comment]
Confirmed to be an issue with new root implementation, marking it as bug

**Comment by CaptainHalflife** [comment]
I also got the same problem with vanced manager 2.5.1 but when i downgrade to 2.5.0 i got this error instead "Failed to chown apk to system owner"
Android: 8.1.0   magisk: 22

**Comment by X1nto** [comment]
It's already fixed in the source code (38860ace07bd03102839d29b3d5ff4104fdcc627), there's no point in saying "I also have the same issue". "Failed to chown" is related to your system not behaving properly

**Comment by CaptainHalflife** [comment]
Ok sry. Any idea to fix my problem ?

**Comment by X1nto** [comment]
Use nonroot version instead

**Comment by Delphox** [comment]
@CaptainHalflife you can try [the latest auto-compiled version of Manager](https://github.com/YTVanced/VancedManager/suites/2198758371/artifacts/45385659) to see if they fixed your issue, but keep in mind it might have bugs as it's not a final release.

You can also try fully uninstalling the system version first with Magisk's Debloater module. Or use non-root in meantime.

**Comment by CaptainHalflife** [comment]
@Delphox I tried that version of manager but i can't grant root access to it so can't even try. I remove youtube like u suggest and install the root version with manager 2.5.0 but it still don't work

**Comment by Delphox** [comment]
@Delphox I see. Well in this case you'll have to stick to non-root until a new Vanced Manager update is released.

**Comment by walachli** [comment]
Hello i have this problem i can't install the you tube vaned
I can only install the youtube music but i need the youtube vanced 
I get error when i try to install it

https://youtu.be/QKMPn78IoHk

Thanks in advance

**Comment by Delphox** [comment]
@walachli That looks like you don't have enough storage space for it.

**Comment by walachli** [comment]
> @walachli That looks like you don't have enough storage space for it.

I have 10 giga of  space

**Comment by Delphox** [comment]
The log would help the devs for sure. It's weird cuz that allocation error is usually related to space.

**Comment by walachli** [comment]
https://wetransfer.com/downloads/6c60d0511fa0825f353bf77a0fa07c3d20210311200752/c7247b

this is the log


thanks you very much

**Comment by X1nto** [comment]
@walachli sadly this isn't something we can fix, android auto filesystem behaves differently from phones or TVs, making it unable to install split apk files

**Comment by asdsadsaasd12312132** [comment]
I believe the "failed to chown" error is caused by loss of root access. I got the error, checked Magisk, and noticed Magisk got uninstalled.

**Comment by Ghabry** [comment]
Had the same bug.
Can confirm the latest auto build fixes it

**Comment by WhatDoor** [comment]
How did you get the latest auto build?

**Comment by WhatDoor** [comment]
> Had the same bug.
> Can confirm the latest auto build fixes it

How did you get the latest auto build?

**Comment by Ghabry** [comment]
@WhatDoor 
https://github.com/YTVanced/VancedManager/issues/435#issuecomment-792990652

**Comment by X1nto** [comment]
Fixed in 2.6.0
